steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t','gcr.io/coherent-vision-411700/coherent-vision-411700:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t','gcr.io/coherent-vision-411700/coherent-vision-411700:$SHORT_SHA', '.']

 
