runtime: python
env: flex
entrypoint: python main.py

liveness_check:
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 2000

runtime_config:
  python_version: 3
manual_scaling: 
  instances: 1

  

